from __future__ import annotations

from .constants import (
    DEFAULT_CHAT_MODEL,
    DEFAULT_CLUSTER_WINDOW_MONTHS,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_RECOMMENDATION_LIMIT,
    DEFAULT_SEARCH_TOP_K,
    DEFAULT_TREND_PERIOD_GRANULARITY,
    PAPERS_COLLECTION,
    RESEARCH_ENTITIES_COLLECTION,
    TREND_CLUSTER_PERIODS_COLLECTION,
    TREND_CLUSTERS_COLLECTION,
    USER_PROFILES_COLLECTION,
)

__all__: list[str] = [
    "DEFAULT_CHAT_MODEL",
    "DEFAULT_CLUSTER_WINDOW_MONTHS",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_RECOMMENDATION_LIMIT",
    "DEFAULT_SEARCH_TOP_K",
    "DEFAULT_TREND_PERIOD_GRANULARITY",
    "PAPERS_COLLECTION",
    "RESEARCH_ENTITIES_COLLECTION",
    "TREND_CLUSTER_PERIODS_COLLECTION",
    "TREND_CLUSTERS_COLLECTION",
    "USER_PROFILES_COLLECTION",
]
