from __future__ import annotations

PAPERS_COLLECTION = "papers_content_v1"
RESEARCH_ENTITIES_COLLECTION = "research_entities_v1"
TREND_CLUSTERS_COLLECTION = "trend_clusters_v1"
TREND_CLUSTER_PERIODS_COLLECTION = "trend_cluster_periods_v1"
USER_PROFILES_COLLECTION = "user_profiles_v1"

DEFAULT_EMBEDDING_MODEL = "qwen3-embedding"
DEFAULT_CHAT_MODEL = "qwen-3-8b"

DEFAULT_SEARCH_TOP_K = 20
DEFAULT_RECOMMENDATION_LIMIT = 20

DEFAULT_CLUSTER_WINDOW_MONTHS = 12
DEFAULT_TREND_PERIOD_GRANULARITY = "month"

