from __future__ import annotations

KEYWORD_EXTRACTION_TASK = "keyword_extraction"
COLLECT_TOPIC_STATS_TASK = "collect_topic_stats"
BOOTSTRAP_PAPERS_TASK = "bootstrap_papers"
RESUME_BOOTSTRAP_PAPERS_TASK = "resume_bootstrap_papers"
PAPER_INDEXING_TASK = "paper_indexing"
ENTITY_INDEXING_TASK = "entity_indexing"
RECOMPUTE_TOPIC_CLUSTERS_TASK = "recompute_topic_clusters"
CLUSTER_DYNAMICS_RECOMPUTE_TASK = "cluster_dynamics_recompute"
TOPIC_QUARTER_REPORT_TASK = "topic_quarter_report"
USER_PROFILE_RECOMPUTE_TASK = "user_profile_recompute"

KEYWORD_EXTRACTION_QUEUE = "queue:keyword_extraction"
OPENALEX_TOPIC_STATS_QUEUE = "queue:openalex_topic_stats"
OPENALEX_BOOTSTRAP_PAPERS_QUEUE = "queue:openalex_bootstrap_papers"
PAPER_INDEXING_QUEUE = "queue:paper_indexing"
ENTITY_INDEXING_QUEUE = "queue:entity_indexing"
CLUSTER_RECOMPUTE_QUEUE = "queue:cluster_recompute"
CLUSTER_DYNAMICS_RECOMPUTE_QUEUE = "queue:cluster_dynamics_recompute"
TOPIC_QUARTER_REPORT_QUEUE = "queue:topic_quarter_reports"
USER_PROFILE_RECOMPUTE_QUEUE = "queue:user_profile_recompute"
FAILED_TASKS_QUEUE = "queue:failed_tasks"
ML_WORKER_SHUTDOWN_KEY = "ml:worker:shutdown"
ADMIN_COVERAGE_TASK_RESULT_KEY_PREFIX = "admin:data_coverage:result"

CANONICAL_TASK_TYPES = frozenset(
    {
        KEYWORD_EXTRACTION_TASK,
        COLLECT_TOPIC_STATS_TASK,
        BOOTSTRAP_PAPERS_TASK,
        RESUME_BOOTSTRAP_PAPERS_TASK,
        PAPER_INDEXING_TASK,
        ENTITY_INDEXING_TASK,
        RECOMPUTE_TOPIC_CLUSTERS_TASK,
        CLUSTER_DYNAMICS_RECOMPUTE_TASK,
        TOPIC_QUARTER_REPORT_TASK,
        USER_PROFILE_RECOMPUTE_TASK,
    }
)

__all__ = [
    "ADMIN_COVERAGE_TASK_RESULT_KEY_PREFIX",
    "BOOTSTRAP_PAPERS_TASK",
    "CANONICAL_TASK_TYPES",
    "CLUSTER_DYNAMICS_RECOMPUTE_QUEUE",
    "CLUSTER_DYNAMICS_RECOMPUTE_TASK",
    "CLUSTER_RECOMPUTE_QUEUE",
    "COLLECT_TOPIC_STATS_TASK",
    "ENTITY_INDEXING_QUEUE",
    "ENTITY_INDEXING_TASK",
    "FAILED_TASKS_QUEUE",
    "KEYWORD_EXTRACTION_QUEUE",
    "KEYWORD_EXTRACTION_TASK",
    "ML_WORKER_SHUTDOWN_KEY",
    "OPENALEX_BOOTSTRAP_PAPERS_QUEUE",
    "OPENALEX_TOPIC_STATS_QUEUE",
    "PAPER_INDEXING_QUEUE",
    "PAPER_INDEXING_TASK",
    "RECOMPUTE_TOPIC_CLUSTERS_TASK",
    "RESUME_BOOTSTRAP_PAPERS_TASK",
    "TOPIC_QUARTER_REPORT_QUEUE",
    "TOPIC_QUARTER_REPORT_TASK",
    "USER_PROFILE_RECOMPUTE_QUEUE",
    "USER_PROFILE_RECOMPUTE_TASK",
]
